variables:
  IMAGE_ORG: bogdandev
  IMAGE_NAME: xpub-faraday
  REPO_URL: https://gitlab.coko.foundation/xpub/xpub-faraday

stages:
  - build
  - test
  - review
  - docker
  - demo

build:
  image: docker:latest
  stage: build
  script:
    - docker version
    - docker build -t $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA .
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then echo "Not pushing" && exit 0; fi
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - echo "Ignore warning! Cannot perform an interactive login from a non TTY device"
    - docker push $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA

lint:
  image: $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - cd ${HOME}
    - npm run lint

test:
  image: $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - cd ${HOME}
    - npm run test

push:latest:
  image: docker:latest
  stage: docker
  script:
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then echo "Not pushing" && exit 0; fi
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - echo "Ignore warning! Cannot perform an interactive login from a non TTY device"
    - docker build -t $IMAGE_ORG/$IMAGE_NAME:latest --label COMMIT_SHA=$CI_COMMIT_SHA .
    - docker push $IMAGE_ORG/$IMAGE_NAME:latest
  only:
  - master

demo:now:
  image: $IMAGE_ORG/$IMAGE_NAME:latest
  stage: demo
  when: manual
  variables:
    PACKAGE_NAME: xpub-faraday
  only:
    - master
  environment:
    name: $PACKAGE_NAME/demo
    url: $NOW_URL
  script:
    - npm install -g now@latest
    - now $REPO_URL/commit/$CI_COMMIT_SHA
    - echo $NOW_URL