version: '3'

services:
  app:
    image: ygou/xpub-faraday:0.4.0
    build:
      context: .
      dockerfile: ./Dockerfile
    # command: sh -c "cd packages/xpub-faraday && yarn install --frozen-lockfile && ./scripts/wait-for-it.sh postgres:5432 -s -t 40 -- npx pubsweet server"
    # command: sh -c "yarn install --frozen-lockfile && ./scripts/wait-for-it.sh postgres:5432 -s -t 40 -- npx pubsweet server"
    # command: sh -c "./scripts/wait-for-it.sh postgres:5432 -s -t 40 -- npx pubsweet server"
    # working_dir: /home/xpub/packages/xpub-faraday
    command: sh -c "npx pubsweet server"
    ports:
      - ${PORT:-3000}:3000
    # volumes:
    #   - ./:/home/xpub
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PGHOST: postgres
      PGUSER: postgres

  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
    # volumes:
    #   - postgres-volume:/var/lib/postgresql/data
      # - ./scripts/test.sql:/docker-entrypoint-initdb.d/test.sql

# volumes:
#   postgres-volume:

